#include "src/build/build_opt.h"
#include "src/internals.h"
#include "src/lexer.h"
#include "src/nasm_generator.h"
#include "src/node.h"
#include "src/parser.h"
#include "src/string_builder.h"
#include "src/token_list.h"
#include <stdio.h>
#include <stdlib.h>
static const char *version = "v0.1.0";
static ARGDef commands[] = {
    {"Available targets:\n\t* x86_64 nasm"},
    {"Set the path of the output generated by the compiler"},
    {"Display the current version of the compiler installed on this machine"},
    {"Error: No such command"},
};
extern void print_usage(const char *program) {
  fprintf(stdout, "USAGE:  %s [OPTIONS] <path-to-file>", program);
  fprintf(stdout, "\nOPTIONS:");
  fprintf(stdout,
          "\n    --help        | -h                 print this message");
  fprintf(stdout, "\n    --output      | -o                 set output path");
  fprintf(stdout, "\n    --version     | -v                 display version");
  fprintf(stdout,
          "\n    --target      | -t                 set target output: see "
          "--help target");
  fprintf(stdout, "\n    --build       |                    build a project "
                  "that was initialized by the compiler");
  fprintf(stdout, "\n    --init        |                    initialize a "
                  "project in \033[33mcurrent directory\033[0m");
  fprintf(stdout,
          "\n    --run         |                    run an executable built by "
          "the compiler for a project initialized by the compiler");
  fprintf(stdout,
          "\n    --build-run   |                    runs --build and --run");
  fprintf(stdout,
          "\n    --clean       |                    clean artifacts made by "
          "the compiler's build system");
  fprintf(stdout,
          "\n    -c            |                    Compile to object file");
  fprintf(stdout,
          "\n    -s            |                    Compile to assembly");
  fprintf(stdout, "\n");
}
bool TIX_DEBUG_ENABLED;
int main(int argc, char **argv) {
  TIX_DEBUG_ENABLED = false;
  BuildOptions bld = {.show_help = false, .show_version = false};
  parse_arguments(&bld, argc, argv);
  TIX_DEBUG_ENABLED = bld.verbose;
  if (bld.show_help && !bld.help_target) {
    print_usage(argv[0]);
    exit(1);
  } else if (bld.has_specialized_help_target) {
    printf("%s\n", commands[bld.help_target].help);
    exit(1);
  }
  if (bld.show_version) {
    printf("version: %s\n", version);
    exit(1);
  }
  TLexer lexer;
  if (tix_lexer_init(&lexer, bld.inputfile) != 0) {
    return EXIT_FAILURE;
  }
  Token token;
  TokenList tokens = {0};
  token_list_init(&tokens);
  do {
    token = tix_lexer_next_token(&lexer);
    print_token(token);
    token_list_add(&tokens, token);
  } while (token.kind != TEOF);
  TParser p;
  stream_max = TString_cstr_to_cstr_array(lexer.stream, &p.source);

  Program pr;
  program_init(&pr);
  parser_init(&p, &tokens);
  parser_parse(&p, &pr);
  NASM64_generator *gen;
  NASM64_init(&gen, pr, p.source, &bld);
  NASM64_generate(gen);
  NASM64_deinit(gen);
  // TODO: tidy this mess
  extern StringBuilder *nasm_out;
  switch (bld.stage) {
  case ASM: {
    char path[128] = {0};
    sprintf(path, "%s.s", bld.outputfile);
    FILE *s = fopen(path, "w");
    fprintf(s, "%s", nasm_out->data);
    fclose(s);
    TIX_LOG(stdout, Finished, "Output: '%s.s'", bld.outputfile);
    return EXIT_SUCCESS;
  }
  case OBJ: {
    char path[128] = {0};
    sprintf(path, "%s.s", bld.outputfile);
    FILE *s = fopen(path, "w");
    fprintf(s, "%s", nasm_out->data);
    fclose(s);
    StringBuilder *cmd;
    SB_init(&cmd);
    SB_set(cmd, "nasm -felf64 -g -dwarf %s.s -o %s.o", bld.outputfile,
           bld.outputfile);
    system(cmd->data);
    SB_set(cmd, "rm %s.s", bld.outputfile, bld.outputfile);
    system(cmd->data);
    TIX_LOG(stdout, Finished, "Output: '%s.o'", bld.outputfile);
    return EXIT_SUCCESS;
  }
  case EXE: {
    char path[128] = {0};
    sprintf(path, "%s.s", bld.outputfile);
    FILE *s = fopen(path, "w");
    fprintf(s, "%s", nasm_out->data);
    fclose(s);
    StringBuilder *cmd;
    SB_init(&cmd);
    SB_set(cmd, "nasm -felf64 -g -dwarf %s.s -o %s.o", bld.outputfile,
           bld.outputfile);
    int status = system(cmd->data);
    if (WIFEXITED(status)) {
      int code = WEXITSTATUS(status);
      if (code != 0) {
      TIX_LOG(stderr, ERROR, "Fatal Error during compilation");
      exit(1);
      }
    }
    SB_set(cmd, "ld %s.o libtix.a -o %s", bld.outputfile, bld.outputfile);
    system(cmd->data);
    SB_set(cmd, "rm %s.s %s.o", bld.outputfile, bld.outputfile);
    system(cmd->data);
    TIX_LOG(stdout, Finished, "Output: '%s'", bld.outputfile);
    return EXIT_SUCCESS;
  }
  }
}
